title: Hello, world! I'm Lucas Ruchel
description: > # this means to ignore newlines until "baseurl:"
  Blog project to share and document my learnings and interesting stuffs.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lucasruchel.com.br" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lucas Ruchel # add your name
author-img: lucas-ruchel.png # add your photo
about-author: I am a system admin that is looking for new and exciting tecnologies. I love swimming and sports.  # add description
social-github: lucasruchel # add your Github handle
social-linkedin: lucas-ruchel-a42aa198/ # add your Linkedin handle
social-email: lukasruchel@gmail.com # add your Email address



# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
