title: Hello, world! I'm Lucas Ruchel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://lucasruchel.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lucas Ruchel # add your name
author-img: lucas-ruchel.jpg # add your photo
about-author: I am a system admin that is looking for new and exciting tecnologies. I love swimming and sometimes go to the gym.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lucasruchel # add your Github handle
social-linkedin: https://www.linkedin.com/in/lucas-ruchel-a42aa198/ # add your Linkedin handle
social-email: lukasruchel@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
